import { Inter } from "next/font/google";
import "./globals.css";
import GlobalState from "./context/globalState";
import CommonLayout from "./components/CommonLayout";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GraphQl",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <CommonLayout>{children}</CommonLayout>
        </GlobalState>
      </body>
    </html>
  );
}
